[theme]
primaryColor = "#14B8A6"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
runOnSave = false
maxUploadSize = 10

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
